# permissions for end users to view partitionnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: partitionnode-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-pangu
    app.kubernetes.io/part-of: kube-pangu
    app.kubernetes.io/managed-by: kustomize
  name: partitionnode-viewer-role
rules:
- apiGroups:
  - partition.kube-pangu.io
  resources:
  - partitionnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - partition.kube-pangu.io
  resources:
  - partitionnodes/status
  verbs:
  - get
