# permissions for end users to edit partitionconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: partitionconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-pangu
    app.kubernetes.io/part-of: kube-pangu
    app.kubernetes.io/managed-by: kustomize
  name: partitionconfig-editor-role
rules:
- apiGroups:
  - partition.kube-pangu.io
  resources:
  - partitionconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - partition.kube-pangu.io
  resources:
  - partitionconfigs/status
  verbs:
  - get
